name: 构建并推送

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-shared.yml
    with:
      profile: release
    secrets:
      HARBOR_SECRET: ${{ secrets.HARBOR_SECRET }}
