name: 构建并推送-Debug

on:
  push:
    branches:
      - debug
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/_build-shared.yml
    with:
      profile: debug
    secrets:
      HARBOR_SECRET: ${{ secrets.HARBOR_SECRET }}
